// add player count as value at game key
module.exports = {
  A1D4: {
    playerCount: 0,
    dbGameID: null,
    proposalResults: [],
    pal3000: null,
    roster: null,
  },
  X3ZK: {
    playerCount: 0,
    dbGameID: null,
    proposalResults: [],
    pal3000: null,
    roster: null,
  },
  B5R9: {
    playerCount: 0,
    dbGameID: null,
    proposalResults: [],
    pal3000: null,
    roster: null,
  },
  F9K0: {
    playerCount: 0,
    dbGameID: null,
    proposalResults: [],
    pal3000: null,
    roster: null,
  },
  J4H8: {
    playerCount: 0,
    dbGameID: null,
    proposalResults: [],
    pal3000: null,
    roster: null,
  },
  V7N5: {
    playerCount: 0,
    dbGameID: null,
    proposalResults: [],
    pal3000: null,
    roster: null,
  },
  C6FR: {
    playerCount: 0,
    dbGameID: null,
    proposalResults: [],
    pal3000: null,
    roster: null,
  },
  N9M6: {
    playerCount: 0,
    dbGameID: null,
    proposalResults: [],
    pal3000: null,
    roster: null,
  },
  E6S5: {
    playerCount: 0,
    dbGameID: null,
    proposalResults: [],
    pal3000: null,
    roster: null,
  },
  G6U2: {
    playerCount: 0,
    dbGameID: null,
    proposalResults: [],
    pal3000: null,
    roster: null,
  },
};
