const SCIENTIST_ROUND_WIN = 'SCIENTIST_ROUND_WIN';
const INFILTRATOR_ROUND_WIN = 'INFILTRATOR_ROUND_WIN';
const RESTART_GAME = 'RESTART_GAME';
const INCREMENT_FAIL = 'INCREMENT_FAIL';
const RESET_FAIL = 'RESET_FAIL';
const INCREMENT_ROUND = 'INCREMENT_ROUND';

module.exports = {
  SCIENTIST_ROUND_WIN,
  INFILTRATOR_ROUND_WIN,
  RESTART_GAME,
  INCREMENT_FAIL,
  RESET_FAIL,
  INCREMENT_ROUND
};