const SCIENTIST_ROUND_WIN = 'SCIENTIST_ROUND_WIN';
const INFILTRATOR_ROUND_WIN = 'INFILTRATOR_ROUND_WIN';
const RESTART_GAME = 'RESTART_GAME';

module.exports = {
  SCIENTIST_ROUND_WIN,
  INFILTRATOR_ROUND_WIN,
  RESTART_GAME
}