const UPDATE_USER = 'UPDATE_PLAYERS';
const ADD_NEW_USER = 'ADD_NEW_USER';
const SET_USERNAME = 'SET_USERNAME';
const ASSIGN_ROLES = 'ASSIGN_ROLES';

module.exports = {
  UPDATE_USER,
  ADD_NEW_USER, 
  SET_USERNAME,
  ASSIGN_ROLES
};